### ISSUE TITLE
Issue using the SDK

### ISSUE THREAD

**Issue by AlmogCohen** [algosec/algosec-python#31]
I'm reposting @julien2404 post from [here](https://github.com/algosec/algosec-python/commit/b419728cb4d1148d15c059e32ca618ff1be2eff0#commitcomment-30461852) for proper tracking of issues. I'll follow up with a response.

> 
> Hi,
> 
> I've installed the latest client version V1.1.0 and started writting a little script. However I'm getting an error.
> Here is the script :
> 
> #!/opt/rh/rh-python36/root/usr/bin/python
> 
> from algosec.api_clients.firewall_analyzer import FirewallAnalyzerAPIClient
> 
> ip='XX.XX.XX.XX'
> username='admin'
> password='hidexxx'
> verify_ssl=0
> 
> source='YY.YY.YY.YY'
> dest='ZZ.ZZ.ZZ.ZZ'
> service='tcp/80'
> 
> client = FirewallAnalyzerAPIClient(ip, username, password, verify_ssl)
> query_result = client.run_traffic_simulation_query(source,dest,service)
> here is the error :
> 
> <suds.sax.document.Document object at 0x7f883954aac8>
> Traceback (most recent call last):
> File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/suds_requests.py", line 16, in wrapper
> return f(*args, **kwargs)
> File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/suds_requests.py", line 54, in send
> resp.raise_for_status()
> File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
> raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error - AFA for url: https://XX.XX.XX.XX/AFA/php/ws.php
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/suds/client.py", line 613, in send
> reply = self.options.transport.send(request)
> File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/suds_requests.py", line 22, in wrapper
> buf,
> suds.transport.TransportError: Error in requests
> Traceback (most recent call last):
> File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/suds_requests.py", line 16, in wrapper
> return f(*args, **kwargs)
> File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/suds_requests.py", line 54, in send
> resp.raise_for_status()
> File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
> raise HTTPError(http_error_msg, response=self)
> 
> Question : is the URL correct : https://XX.XX.XX.XX/AFA/php/ws.php ? I saw in algosec doc that the URL must be https://XX.XX.XX.XX/AFA/php/ws.php?wsdl
> 
> I'm not sure if I'm writting this comment in the good section. Feel free to tell me.
> 
> Thank you in advance

**Comment by julien2404** [comment]
Hi,
Thank you very much for your answer. 
I'm thinking about the version of Algosec. Could this be related to the version ?

Here are the versions:

Appliance version | v2017.2.0-b34
Firewall Analyzer version | v2017.2.100-b31

Which version are running ?

Thanks

**Comment by AlmogCohen** [comment]
Debugging this issue together I've implemented https://github.com/algosec/algosec-python/pull/32 for better logging and error messages for SOAP.

As part of these improvements, every SOAP message that is sent/received is logged with DEBUG level. To enable it in future cases or if anybody wants to inspect the SOAP message one-by-one, simply do this before you run your code: `logging.getLogger('algosec').setLevel(logging.DEBUG)`

**Comment by AlmogCohen** [comment]
Yes! I'm so happy to hear that! Happy we can make it happen...

I've forwarded your question I'll see what the people here say :) Hope I can help.

If you have any questions about the AlgoSec SDK/system just let me know!
