### ISSUE TITLE
incorrect documentation: import firewall analyzer

### ISSUE THREAD

**Issue by JeanFrancoisMaes** [algosec/algosec-python#40]
In the documentation the step to import the firewallanalyzerapiclient is wrong
it states: `from algosec.api_clients import FirewallAnalyzerAPIClient` while it should be ` from algosec.api_clients.firewall_analyzer import FirewallAnalyzerAPIClient `

**Comment by AlmogCohen** [comment]
Thanks @JeanFrancoisMaes! 

- I've refactored the SDK and forgot fixing the examples. I fixed it now.
- Seems like the devs have heard your message https://github.com/algosec/algosec-python/pull/41 :) It would soon be available in the release. Hope you'll find it helpful.

**Comment by AlmogCohen** [comment]
@JeanFrancoisMaes version 1.2.2 is now up with your feature request builtin. It is unittested + tested against my demo machine + pushed to PyPi and on the master branch here. Enjoy!

**Comment by JeanFrancoisMaes** [comment]
:+1:  thanks @AlmogCohen
