### ISSUE TITLE
export simulation to pdf

### ISSUE THREAD

**Issue by JeanFrancoisMaes** [algosec/algosec-python#42]
Hi there Algosec Team 

I was wondering if there is a way to export the query to pdf from this python SDK?

**Comment by AlmogCohen** [comment]
You mean from the web UI?

**Comment by JeanFrancoisMaes** [comment]
yes, the functionality to export to pdf via the rest api
or should  I use a library like pdfkit for this? :)

thanks for the switft responses by the way!

**Comment by AlmogCohen** [comment]
Anytime friend :)

There is no built-in way to do that but I hope that `pdfkit` way would work for you. Remember that you must be logged in. You can mix `requests` and `pdfkit` to do it as described in [StackOverflow answer](https://stackoverflow.com/a/44581668/1407575).

To login into AlgoSec you can simply use the `requests` package the same way we do it in the BusinessFlow Client as you can see [here](https://github.com/algosec/algosec-python/blob/master/algosec/api_clients/business_flow.py#L68) and mix it with the `pdfkit`

Please do let me know if I can help in any way :)

**Comment by JeanFrancoisMaes** [comment]
Hey @AlmogCohen 

I have not tested it out yet, but will do it in the coming week :-) 
I'll keep you posted, this issue does not have to remain open 
this could potentially be a feature request? :-)

**Comment by AlmogCohen** [comment]
:)
