### ISSUE TITLE
REST API and API Guide

### ISSUE THREAD

**Issue by dnascimento** [algosec/algosec-python#48]
Where may I find the API guide for REST and SOAP?

**Comment by AlmogCohen** [comment]
Hi @dnascimento, sorry for responding after such a long time. I've somehow missed your message.

The full API guide for both REST and SOAP could be found on the AlgoSec portal -> Documentation -> AlgoSec Security Management Suite (ASMS) Manuals -> API Guide. Choose the relevant API Guide for your AlgoSec ASMS version.

Hope it does help. Let me know if any help is still needed

**Comment by AlmogCohen** [comment]
Hope it helped! The issue is closed for now :) Let me know if you need any help
